const schema = {
    name:'adminTall',
    version:2,
    collection:[
        {
            name:'company',
            datos:[
                {
                    indice:'nombre',
                    unico:true,
                },
                {
                    indice:'nit',
                    unico:true
                },
                {
                    indice:'numero',
                    unico:true
                },
                {
                    indice:'direccion',
                    unico:true
                },
                {
                    indice:'ciudad',
                    unico:true
                }
            ]
        },
        {
            name:'tareas',
            datos:[
                {
                    indice:'fecha',
                    unico:false
                }, 
                {
                    indice:'creador',
                    unico:false,
                },
                {
                    indice:'usuario',
                    unico:false
                }, 
                {
                    indice:'tarea',
                    unico:false,
                },
                {
                    indice:'completada',
                    unico:false
                }
            ]
        },
        {
            name:'clientes',
            datos:[
                {
                    indice:'nombre',
                    unico:true
                },
                {
                    indice:'nit',
                    unico:true
                },
                {
                    indice:'telefono',
                    unico:true,
                },
                {
                    indice:'direccion',
                    unico:true
                },
                {
                    indice:'servicio',
                    unico:false
                }
            ]
        },
        {
            name:'usuarios',
            datos:[
                {
                    indice:'name',
                    unico:true
                },
                {
                    indice:'nit',
                    unico:true
                },
                {
                    indice:'tel',
                    unico:true
                },
                {
                    indice:'email',
                    unico:true
                },
                {
                    indice:'pass',
                    unico:false
                }
            ]
        },
        {
            name:'lotes',
            datos:[
                {
                    indice:'cliente',
                    unico:false
                },
                {
                    indice:'ref',
                    unico:true
                },
                {
                    indice:'lote',
                    unico:false
                },
                {
                    indice:'valor',
                    unico:false
                },
                {
                    indice:'insumos',
                    unico:false
                },
                {
                    indice:'info',
                    unico:false
                },
                {
                    indice:'descripcion',
                    unico:false
                },
                {
                    indice:'fecha',
                    unico:false,
                },
                {
                    indice:'pendiente',
                    unico:false
                },
                {
                    indice:'afectado',
                    unico:false
                }
            ]
        },
        {
            name:'facturas',
            datos:[
                {
                    indice:'numeroFact',
                    unico:true
                },
                {
                    indice:'fechaEmit',
                    unico:false
                },
                {
                    indice:'namePro',
                    unico:false
                },
                {
                    indice:'nameCli',
                    unico:false
                },
                {
                    indice:'concepto',
                    unico:false
                }
            ]
        }
    ]
}
export default schema